"""Define new parameters here.

By being explict about parameters, it will be easier to share
information around the team.

All generator and model functions should take in **kwargs as an argument.
"""
import typing

from dataclasses import dataclass


# TODO(#65): Implement this config
@dataclass
class PreprocessConfig:
    pass


@dataclass
class DataConfig:
    # A directory containing a list of numpy files with
    # patient ID as their filename
    data_dir: str
    # A CSV file generated by saving a pandas DataFrame
    labels_path: str
    index_col: str
    label_col: str


@dataclass
class ModelConfig:
    # Should return a model and must take in **kwargs as an argument
    model_callable: typing.Callable
    optimizer: typing.Callable
    loss: typing.Callable

    dropout_rate1: int = 0.8
    dropout_rate2: int = 0.8
    freeze: bool = False


@dataclass
class GeneratorConfig:
    # Should return a tuple containing x_train, y_train, x_test, y_test
    # Must take in **kwargs as an argument
    generator_callable: typing.Callable
    rotation_range: int = 30
    width_shift_range: float = 0.1
    height_shift_range: float = 0.1
    shear_range: float = 0
    zoom_range: int = 0.1
    horizontal_flip: bool = True
    vertical_flip: bool = False


# Keep the below two classes in sync

@dataclass
class ParamConfig:
    data: DataConfig
    generator: GeneratorConfig
    model: ModelConfig
    batch_size: int
    seed: int
    val_split: float

    job_fn: typing.Callable = None


@dataclass
class ParamGrid:
    data: typing.Tuple[DataConfig]
    generator: typing.Tuple[GeneratorConfig]
    model: typing.Tuple[ModelConfig]
    batch_size: typing.List[int]
    seed: typing.Tuple[int]
    val_split: typing.Tuple[int]

    job_fn: typing.Callable = None

    def __init__(self, **kwargs):
        for attr in kwargs:
            if attr not in ParamGrid.__dataclass_fields__:
                raise ValueError(
                    '{} is not an attribute of ParamGrid'.format(attr))

        # TODO(#65): Implement preprocessing config
        if not isinstance(kwargs['data'], DataConfig):
            data = tuple(
                DataConfig(**d) for d in kwargs['data'])
            self.data = data
        if not isinstance(kwargs['generator'], GeneratorConfig):
            generators = tuple(
                GeneratorConfig(**gen) for gen in kwargs['generator'])
            self.generator = generators
        if not isinstance(kwargs['model'], ModelConfig):
            models = tuple(ModelConfig(**mod) for mod in kwargs['model'])
            self.model = models

        self.seed = kwargs['seed']
        self.val_split = kwargs['val_split']
        self.batch_size = kwargs['batch_size']

        if 'job_fn' in kwargs:
            self.job_fn = kwargs['job_fn']


if set(ParamConfig.__dataclass_fields__.keys()) \
        != set(ParamGrid.__dataclass_fields__.keys()):
    raise ValueError(
        'ParamConfig and ParamGrid do not have the same properties')
